-- MySQL Script generated by MySQL Workbench
-- jeu. 26 janv. 2023 17:12:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portfolio`;
-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8mb4;
USE `portfolio`;
-- -----------------------------------------------------
-- Table `portfolio`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`user`;
CREATE TABLE IF NOT EXISTS `portfolio`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `hashedPassword` VARCHAR(255) NOT NULL,
  `role` ENUM('ADMIN', 'USER') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `portfolio`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`image`;
CREATE TABLE IF NOT EXISTS `portfolio`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(255) NOT NULL,
  `description` VARCHAR(45),
  `creationDate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `portfolio`.`projet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`projet`;
CREATE TABLE IF NOT EXISTS `portfolio`.`projet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `detail` VARCHAR(45) NULL,
  `lien` VARCHAR(45) NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projet_image_idx` (`image_id` ASC) VISIBLE,
  CONSTRAINT `fk_projet_image` FOREIGN KEY (`image_id`) REFERENCES `portfolio`.`image` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;